services:
  - type: web
    name: ai-image-generator
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: STABILITY_API_KEY
        sync: false
      - key: PORT
        value: 10000
